### ISSUE TITLE
To-do list for me

### ISSUE THREAD

**Issue by heipizhu4** [heipizhu4/Nation-of-Nuke#1]
- [x] #2
- [x] Make sure the religion is spreading. Fixed by 
commit [47ba76f](https://github.com/heipizhu4/Nation-of-Nuke/commit/47ba76f3cfc829b7d92b2b0f6c1640f60007996b)
- [x] A unit for paradrop & annex cities #5 
- [ ] Add a spirit for city annexer
- [x] Make everything purchasble
- [ ] Add a compartively smaller map for phones
- [ ] Do the trans

**Comment by RealBamboolord** [comment]
Take a look at the purchase stuff, its not optimal yet

**Comment by RealBamboolord** [comment]
I made a final purchase update, go review and merge it :)
